FROM websphere-liberty:kernel
COPY ./acmeair-mainapp/server.xml /config/
RUN installUtility install --acceptLicense defaultServer

EXPOSE 80
ENV VCAP_APP_PORT=80
ENV SERVICE_NAME=main

ADD ./acmeair-mainapp/build/libs/acmeair-mainapp-2.0.0-SNAPSHOT.war /config/apps/
