FROM websphere-liberty:kernel
COPY server.xml /config/
RUN installUtility install --acceptLicense defaultServer

EXPOSE 9080
ENV VCAP_APP_PORT=9080
#ENV CCS_BIND_APP=MongoBridge
#ENV SERVICE_NAME=auth-java
#ENV SD_URL=https://servicediscovery.ng.bluemix.net
#ENV SD_TOKEN=1m3rliolucbampleoq36am82bdfv0othuruoefe6enop27ab7cnp

ADD acmeair-cs-2.0.0-SNAPSHOT.war /config/apps/
